
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "tk_and tk_as tk_call tk_cmts_block tk_cmts_line tk_create tk_discard tk_do tk_export tk_file tk_from tk_id tk_import tk_join tk_key tk_limit tk_nome tk_num tk_operator tk_prcedure tk_print tk_rename tk_reserved tk_select tk_table tk_using tk_wherePROG  : CMDLIST CMDLIST  : CMD CMDLIST  : CMD CMDLIST   CMD  : CONF      CONF  : tk_import tk_table tk_id tk_from tk_file ';'"
    
_lr_action_items = {'tk_import':([0,3,4,11,],[5,5,-4,-5,]),'$end':([1,2,3,4,6,11,],[0,-1,-2,-4,-3,-5,]),'tk_table':([5,],[7,]),'tk_id':([7,],[8,]),'tk_from':([8,],[9,]),'tk_file':([9,],[10,]),';':([10,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PROG':([0,],[1,]),'CMDLIST':([0,3,],[2,6,]),'CMD':([0,3,],[3,3,]),'CONF':([0,3,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PROG","S'",1,None,None,None),
  ('PROG -> CMDLIST','PROG',1,'p_p1','grammar.py',66),
  ('CMDLIST -> CMD','CMDLIST',1,'p_p2','grammar.py',70),
  ('CMDLIST -> CMD CMDLIST','CMDLIST',2,'p_p3','grammar.py',74),
  ('CMD -> CONF','CMD',1,'p_p4','grammar.py',78),
  ('CONF -> tk_import tk_table tk_id tk_from tk_file ;','CONF',6,'p_p9','grammar.py',82),
]
